version: '2'
services:
  nid_aux_histoires-app:
    image: nid_aux_histoires
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://nid_aux_histoires-mariadb:3306/nid_aux_histoires?useLegacyDatetimeCode=false&serverTimezone=UTC
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  nid_aux_histoires-mariadb:
    extends:
      file: mariadb.yml
      service: nid_aux_histoires-mariadb
